stages:
  - build

job1:
  stage: build
  script:
    - git clone --depth 1 https://github.com/wclimb/blog.git
    - cd blog
    - cnpm i
    - hexo g
    - cp -rf ./public/* /home/www/wclimb/
  only:
    - master
  tags:
    - my-tag
